// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_application_1/test/model/client/article_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_application_1/model/client/article.dart' as _i3;
import 'package:flutter_application_1/model/response/article.dart' as _i5;
import 'package:flutter_application_1/model/response/article_detail.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleDetailResponse_0 extends _i1.SmartFake
    implements _i2.ArticleDetailResponse {
  _FakeArticleDetailResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticleListClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleListClient extends _i1.Mock implements _i3.ArticleListClient {
  MockArticleListClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ArticleListResponse>> fetchArticleList() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArticleList,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ArticleListResponse>>.value(
            <_i5.ArticleListResponse>[]),
      ) as _i4.Future<List<_i5.ArticleListResponse>>);
  @override
  _i4.Future<_i2.ArticleDetailResponse> fetchArticleDetail(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArticleDetail,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.ArticleDetailResponse>.value(
            _FakeArticleDetailResponse_0(
          this,
          Invocation.method(
            #fetchArticleDetail,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.ArticleDetailResponse>);
}
